### ISSUE TITLE
Crontab generation issue

### ISSUE THREAD

**Issue by bartoszkubicki** [ORBA/magento2-codegen#1]
Thanks for providing such an useful tool for community. I have just started testing it around and found tiny issues. 

While answering questions about crontab.xml file I couldn't insert value 0 for scheduleHour. I bet the same issue may occur for other parts of crontab expression. Maybe 0 is casted to null or sth like this and it is not accepted as value is required.

Generated crontab not exactly matches what I've inserted through CLI. Job name is prepended with snake case module name, what was for me unexpected.

**Comment by michalbiarda** [comment]
Thanks for kind words. We'll check the issue.

**Comment by michalbiarda** [comment]
@bartoszkubicki The issue was fixed in the newset release 3.2.0.
