### ISSUE TITLE
Empty copyrights

### ISSUE THREAD

**Issue by bartoszkubicki** [ORBA/magento2-codegen#2]
Thanks for providing such an useful tool for community. 

Adding additional flag like "includeCompanyHeader" would be useful as not all companies includes company name and exact author data. Adding empty values doesn't prevent adding copyrights notes in headers and they look like this:
```
<!--
/**
 * @copyright Copyright ©  . All rights reserved.
 * @author
 */
-->
```

**Comment by michalbiarda** [comment]
That's a very nice idea. Thanks!

**Comment by michalbiarda** [comment]
@bartoszkubicki In the new release 3.2.0 we have added new config properties that allow you configure generated files headers whatever you want. See: https://github.com/ORBA/magento2-codegen/blob/c470356097e2339c465e6b740c0a1f41719cd809/config/codegen.yml.dist
